
#Un poco de bucle while en nuestro texto asies xd
llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados = 0
while llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados <= 15:
	print(llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados)
	llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados += 5

while llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados >= -100:
	print(llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados)
	llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecados -= 20

llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecadosremastered = 10
while llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecadosremastered >= 0:
	print('El valor de llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecadosremastered es: ', llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecadosremastered, ' xd') #THE LONG WAAAAAYYYYYYYYY
	llamaradaardientedelfuegoeternodelinfiernoendondenospudriremostodospornuestrospecadosremastered -= 1